controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
hello_world:
    path: /world/hello
    controller: App\Controller\WorldController::hello

hello_answer:
    path: /world/answer
    controller: App\Controller\WorldController::answer

request:
    path: /request/start
    controller: App\Controller\RequestController::start