<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250226155635 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE course (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, teacher_id BIGINT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_169E6FB941807E1D ON course (teacher_id)');
        $this->addSql('CREATE TABLE lesson (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(50) NOT NULL, orderNum INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, course_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F87474F3591CC992 ON lesson (course_id)');
        $this->addSql('CREATE INDEX inx__lesson__course_id__id ON lesson (course_id, id)');
        $this->addSql('CREATE TABLE lesson_content (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lesson_id BIGINT DEFAULT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BB9620ECDF80196 ON lesson_content (lesson_id)');
        $this->addSql('CREATE TABLE text_lesson_content (text TEXT NOT NULL, id BIGINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "user" (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, login VARCHAR(32) NOT NULL, password VARCHAR(100) NOT NULL, full_name VARCHAR(256) NOT NULL, age INT NOT NULL, is_active BOOLEAN NOT NULL, email VARCHAR(100) DEFAULT NULL, phone VARCHAR(100) DEFAULT NULL, roles JSON NOT NULL, token VARCHAR(32) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D6495F37A13B ON "user" (token)');
        $this->addSql('CREATE TABLE student_course (user_id BIGINT NOT NULL, course_id BIGINT NOT NULL, PRIMARY KEY(user_id, course_id))');
        $this->addSql('CREATE INDEX IDX_98A8B739A76ED395 ON student_course (user_id)');
        $this->addSql('CREATE INDEX IDX_98A8B739591CC992 ON student_course (course_id)');
        $this->addSql('CREATE TABLE video_lesson_content (video_url VARCHAR(255) NOT NULL, id BIGINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB941807E1D FOREIGN KEY (teacher_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lesson ADD CONSTRAINT FK_F87474F3591CC992 FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lesson_content ADD CONSTRAINT FK_BB9620ECDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE text_lesson_content ADD CONSTRAINT FK_C17F8E19BF396750 FOREIGN KEY (id) REFERENCES lesson_content (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_course ADD CONSTRAINT FK_98A8B739A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_course ADD CONSTRAINT FK_98A8B739591CC992 FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_lesson_content ADD CONSTRAINT FK_2D6B288EBF396750 FOREIGN KEY (id) REFERENCES lesson_content (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE course DROP CONSTRAINT FK_169E6FB941807E1D');
        $this->addSql('ALTER TABLE lesson DROP CONSTRAINT FK_F87474F3591CC992');
        $this->addSql('ALTER TABLE lesson_content DROP CONSTRAINT FK_BB9620ECDF80196');
        $this->addSql('ALTER TABLE text_lesson_content DROP CONSTRAINT FK_C17F8E19BF396750');
        $this->addSql('ALTER TABLE student_course DROP CONSTRAINT FK_98A8B739A76ED395');
        $this->addSql('ALTER TABLE student_course DROP CONSTRAINT FK_98A8B739591CC992');
        $this->addSql('ALTER TABLE video_lesson_content DROP CONSTRAINT FK_2D6B288EBF396750');
        $this->addSql('DROP TABLE course');
        $this->addSql('DROP TABLE lesson');
        $this->addSql('DROP TABLE lesson_content');
        $this->addSql('DROP TABLE text_lesson_content');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE student_course');
        $this->addSql('DROP TABLE video_lesson_content');
    }
}
