<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250429152123 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE course (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, price NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, teacher_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_169E6FB941807E1D ON course (teacher_id)');
        $this->addSql('CREATE TABLE installment_payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(10, 2) NOT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, paid BOOLEAN NOT NULL, payment_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EDA1D60B4C3A3BB ON installment_payment (payment_id)');
        $this->addSql('CREATE TABLE lesson (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(50) NOT NULL, orderNum INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, course_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F87474F3591CC992 ON lesson (course_id)');
        $this->addSql('CREATE INDEX inx__lesson__course_id__id ON lesson (course_id, id)');
        $this->addSql('CREATE TABLE lesson_content (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lesson_id BIGINT DEFAULT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BB9620ECDF80196 ON lesson_content (lesson_id)');
        $this->addSql('CREATE TABLE lesson_revision (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lesson_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX inx__lesson_revision__lesson_id ON lesson_revision (lesson_id)');
        $this->addSql('CREATE INDEX inx__lesson_revision__title ON lesson_revision (title)');
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total_amount NUMERIC(10, 2) NOT NULL, discount_applied NUMERIC(10, 2) DEFAULT NULL, is_installment BOOLEAN NOT NULL, installment_months INT DEFAULT NULL, status VARCHAR(50) NOT NULL, is_fully_paid BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id BIGINT NOT NULL, course_id BIGINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6D28840DA76ED395 ON payment (user_id)');
        $this->addSql('CREATE INDEX IDX_6D28840D591CC992 ON payment (course_id)');
        $this->addSql('CREATE TABLE student_task_revision (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id BIGINT DEFAULT NULL, task_id BIGINT DEFAULT NULL, revision_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_783F071E1DFA7C8F ON student_task_revision (revision_id)');
        $this->addSql('CREATE INDEX inx__student_task_revision__user_id ON student_task_revision (user_id)');
        $this->addSql('CREATE INDEX inx__student_task_revision__task_revision_id ON student_task_revision (task_id)');
        $this->addSql('CREATE INDEX inx__student_task_revision__task_id__revision_id ON student_task_revision (task_id, revision_id)');
        $this->addSql('CREATE TABLE task (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lesson_id BIGINT DEFAULT NULL, current_revision_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_527EDB25A32ED756 ON task (current_revision_id)');
        $this->addSql('CREATE INDEX inx__task__lesson_id ON task (lesson_id)');
        $this->addSql('CREATE TABLE task_revision (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(100) NOT NULL, text TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, task_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX inx__task_revision__task_id ON task_revision (task_id)');
        $this->addSql('CREATE TABLE text_lesson_content (text TEXT NOT NULL, id BIGINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "user" (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, login VARCHAR(32) NOT NULL, password VARCHAR(100) NOT NULL, full_name VARCHAR(256) NOT NULL, age INT NOT NULL, is_active BOOLEAN NOT NULL, email VARCHAR(100) DEFAULT NULL, phone VARCHAR(100) DEFAULT NULL, roles JSON NOT NULL, token VARCHAR(32) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649AA08CB10 ON "user" (login)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D6495F37A13B ON "user" (token)');
        $this->addSql('CREATE TABLE student_course (user_id BIGINT NOT NULL, course_id BIGINT NOT NULL, PRIMARY KEY(user_id, course_id))');
        $this->addSql('CREATE INDEX IDX_98A8B739A76ED395 ON student_course (user_id)');
        $this->addSql('CREATE INDEX IDX_98A8B739591CC992 ON student_course (course_id)');
        $this->addSql('CREATE TABLE video_lesson_content (video_url VARCHAR(255) NOT NULL, id BIGINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB941807E1D FOREIGN KEY (teacher_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE installment_payment ADD CONSTRAINT FK_EDA1D60B4C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lesson ADD CONSTRAINT FK_F87474F3591CC992 FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lesson_content ADD CONSTRAINT FK_BB9620ECDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lesson_revision ADD CONSTRAINT FK_25245FD5CDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D591CC992 FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_task_revision ADD CONSTRAINT FK_783F071EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_task_revision ADD CONSTRAINT FK_783F071E8DB60186 FOREIGN KEY (task_id) REFERENCES task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_task_revision ADD CONSTRAINT FK_783F071E1DFA7C8F FOREIGN KEY (revision_id) REFERENCES task_revision (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25CDF80196 FOREIGN KEY (lesson_id) REFERENCES lesson (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25A32ED756 FOREIGN KEY (current_revision_id) REFERENCES task_revision (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE task_revision ADD CONSTRAINT FK_2DA3FF808DB60186 FOREIGN KEY (task_id) REFERENCES task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE text_lesson_content ADD CONSTRAINT FK_C17F8E19BF396750 FOREIGN KEY (id) REFERENCES lesson_content (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_course ADD CONSTRAINT FK_98A8B739A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_course ADD CONSTRAINT FK_98A8B739591CC992 FOREIGN KEY (course_id) REFERENCES course (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_lesson_content ADD CONSTRAINT FK_2D6B288EBF396750 FOREIGN KEY (id) REFERENCES lesson_content (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE course DROP CONSTRAINT FK_169E6FB941807E1D');
        $this->addSql('ALTER TABLE installment_payment DROP CONSTRAINT FK_EDA1D60B4C3A3BB');
        $this->addSql('ALTER TABLE lesson DROP CONSTRAINT FK_F87474F3591CC992');
        $this->addSql('ALTER TABLE lesson_content DROP CONSTRAINT FK_BB9620ECDF80196');
        $this->addSql('ALTER TABLE lesson_revision DROP CONSTRAINT FK_25245FD5CDF80196');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840DA76ED395');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D591CC992');
        $this->addSql('ALTER TABLE student_task_revision DROP CONSTRAINT FK_783F071EA76ED395');
        $this->addSql('ALTER TABLE student_task_revision DROP CONSTRAINT FK_783F071E8DB60186');
        $this->addSql('ALTER TABLE student_task_revision DROP CONSTRAINT FK_783F071E1DFA7C8F');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25CDF80196');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25A32ED756');
        $this->addSql('ALTER TABLE task_revision DROP CONSTRAINT FK_2DA3FF808DB60186');
        $this->addSql('ALTER TABLE text_lesson_content DROP CONSTRAINT FK_C17F8E19BF396750');
        $this->addSql('ALTER TABLE student_course DROP CONSTRAINT FK_98A8B739A76ED395');
        $this->addSql('ALTER TABLE student_course DROP CONSTRAINT FK_98A8B739591CC992');
        $this->addSql('ALTER TABLE video_lesson_content DROP CONSTRAINT FK_2D6B288EBF396750');
        $this->addSql('DROP TABLE course');
        $this->addSql('DROP TABLE installment_payment');
        $this->addSql('DROP TABLE lesson');
        $this->addSql('DROP TABLE lesson_content');
        $this->addSql('DROP TABLE lesson_revision');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE student_task_revision');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE task_revision');
        $this->addSql('DROP TABLE text_lesson_content');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE student_course');
        $this->addSql('DROP TABLE video_lesson_content');
    }
}
